### ISSUE TITLE
Icons for Lunar and Order & Chaos

### ISSUE THREAD

**Issue by Alsciende** [MWDelaney/Netrunner-Icon-Font#9]
Hi Michael. I don't know if you're willing to spend any more time on these icons, but I wanted to let you know that I'm going to use the icons you created for the cycles and deluxes. But, two things:

- I can't find them in the svg folder. Since I added some icons to the collection via IcoMoon (namely, link-half-top and link-half-bottom), when I re-created the font, I lost the icons for the cycles and deluxes.

- The icons for the latest cycle and deluxe are obviously missing. 

I just wanted to check with you, to know if you can find the time to add these, before I set up to do them myself (but I know it will take me much longer).

**Comment by MWDelaney** [comment]
Hi, sorry for the delay.




I would like to update this font with the new expansion icons, but doing so will necessarily rely on finding good versions of them that either already are vectors, or are of high enough quality to convert to vectors. I'll do some looking. If you have sources for them please let me know.




As for the SVGs let me look through what I have. I'll get back to you. 



—

**Comment by MWDelaney** [comment]
Do you have svgs of the icons you added handy? I can add them here and together we'll have a more complete font!

**Comment by Alsciende** [comment]
I do, but I'm struggling to attach svg to this discussion. I'll try to send them to you in some other way.

Concerning the new expansion icons, here is what I found in the latest FAQ.

![anr-spin](https://cloud.githubusercontent.com/assets/391974/6962555/b3af8572-d935-11e4-8410-186ee3b7ce95.png)
![anr-coreset](https://cloud.githubusercontent.com/assets/391974/6962552/b3ae93d8-d935-11e4-8b39-fd27f58d08d8.png)
![anr-genesis](https://cloud.githubusercontent.com/assets/391974/6962553/b3af3590-d935-11e4-8a1e-f8495d56f108.png)
![anr-honorandprofit](https://cloud.githubusercontent.com/assets/391974/6962554/b3af6fec-d935-11e4-8750-eb6bf4aeb966.png)
![anr-lunar](https://cloud.githubusercontent.com/assets/391974/6962556/b3b09b6a-d935-11e4-9580-7ec32ee62ddb.png)
![anr-orderandchaos](https://cloud.githubusercontent.com/assets/391974/6962557/b3b1f6cc-d935-11e4-9182-e15dea70c43b.png)

**Comment by Alsciende** [comment]
(same scale for all icons)

**Comment by Alsciende** [comment]
Half-link icons:
https://www.dropbox.com/s/jw8c90jbhkxmypr/link-half-bottom.svg?dl=0
https://www.dropbox.com/s/re47jjy6tqf0mds/link-half-top.svg?dl=0

**Comment by MWDelaney** [comment]
d2b70fd4184b9390400b03c31c489cb4ae4b2e7c should close this. Let me know if there are any issues. I did these kinda quick and you're much better at spotting inconsistencies with these than I am!

**Comment by alsciende** [comment]
It's perfect. Thank you very much!
